# Generated by Django 3.1.1 on 2020-12-24 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20201224_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeric_fields',
            name='inp_number1',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
