# Generated by Django 3.1.1 on 2021-01-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_auto_20201224_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeric_fields',
            name='operation_text',
            field=models.CharField(default='i', max_length=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
