# Generated by Django 3.1.1 on 2021-01-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20210115_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeric_fields',
            name='result',
            field=models.CharField(max_length=6),
        ),
    ]
